### ISSUE TITLE
Q: what about the rosters / contacts

### ISSUE THREAD

**Issue by joergmschulz** [jsxc/xmpp-cloud-auth#12]
This script looks interesting and moves authentication to NC/OC where it is a good place. 
What about the rosters / contact lists: Will they be fed from the user's personal address book (fine) or from NC/OC group memberships (even better) or from the xmpp server (not so easy, only openfire has a good way to extract group information from LDAP, but I don't see a possibility to add this script to openfire)?

**Comment by sualko** [comment]
There is currently no sync option, because this would probably require to write an extra module. As far as I know there is no api for such a thing in ejabberd or prosody, but would be nice to have.

> I don't see a possibility to add this script to openfire?

That's right. We only support prosody and ejabberd.

**Comment by MarcelWaldvogel** [comment]
@joergmschulz If you create an authentication plugin for Openfire that can use an external command, I'd be happy to create support for it in `external_auth.py`. As long as there is no way to have an external authentication command in Openfire, this module cannot be used directly.

I would recommend that any newly created plugin for external authentication use the prosody syntax, as it is in line with the Unix pipe philosophy. This would also mean that adding that support here would boil down to alias `-t openfire` to `-t prosody`

**Comment by joergmschulz** [comment]
Good idea - Openfire is Java, and I am not into Java, sorry - not being a developer at all (only some quick and dirty unprofessional hacks), I don’t think I am able to do it. Anyway, I’ll have a look as there are auth scripts for OpenFire for SAML or oAuth; maybe it’s easy.

Kind regards
Jörg
