### ISSUE TITLE
Prosody does not allow script arguments

### ISSUE THREAD

**Issue by sualko** [jsxc/xmpp-cloud-auth#2]
Until https://prosody.im/issues/issue/841 is fixed, https://github.com/jsxc/ejabberd-cloud-auth/blob/master/prosody-modules/mod_auth_external.lua can be used.

**Comment by MarcelWaldvogel** [comment]
Obsoleted by 6a200cd0d19d5c4172d7e9cc4aed258f0d1a04b6

**Comment by MarcelWaldvogel** [comment]
"Fixed" by no longer being recommended as of e9a4dc6f7d0cc0a8c7606f0cfba1ae03356fdfa1.

We still hope that the Prosody community will eventually include our patch, as it is useful for other cases.

**Comment by kousu** [comment]
Do you know why https://prosody.im/issues/841 is being forgotten? Is it just lost in there being too many open issues, or was there an argument against your patch?

**Comment by MarcelWaldvogel** [comment]
AFAIK, there was no feedback. We solved it by moving everything to the configuration file, so that options typically are not needed anymore.
