### ISSUE TITLE
Mention somewhere that it depends on lua-lpty

### ISSUE THREAD

**Issue by poVoq** [jsxc/xmpp-cloud-auth#22]
When trying to get this to run using prosody 0.10 with postgres backend (confirmed working with internal user from JSXC Nextcloud) and the new tutorial (which by the way doesn't mention the execution permissions for external_cloud.py so that the prosody user can run it).

One of the things that came up is that there was an error in the log about "lua-lpty" missing. After installing it on my Ubuntu 16.04 VPS where the Prosody server runs (different from the Nextcloud server), I can again log into the Nextcloud instance with the chat enabled.

**Comment by MarcelWaldvogel** [comment]
## Execute permissions

How did you install it? I just did a fresh `git clone https://github.com/jsxc/xmpp-cloud-auth.git` and `external_cloud.py` (and `.sh`) were executable.

## *lua-pty*

It is mentioned in the [Prosody `mod_auth_external.lua` installation instructions](https://modules.prosody.im/mod_auth_external.html) and in the [from-scratch installation instructions in the wiki](https://github.com/jsxc/xmpp-cloud-auth/wiki/installing#on-the-xmpp-server-for-prosody-installations), but not yet in the [README](https://github.com/jsxc/xmpp-cloud-auth/blob/master/README.md). I will add it there as well.

**Comment by poVoq** [comment]
OK, must have overlooked it? Anyways, thanks for the nice work on the tutorial. Really helped!

**Comment by MarcelWaldvogel** [comment]
Originally, the recommendation was to install `mod_auth_external.lua` from the Prosody web site. There the instructions included `lua-lpty`. With the local, modified, module, that somehow was dropped.

I'm glad you like it!
