### ISSUE TITLE
Popup for new users to log-out and log in again for it to work?

### ISSUE THREAD

**Issue by poVoq** [jsxc/xmpp-cloud-auth#23]
It seems like a new user will not work on the first login, but after logging out and then in again it seems to work.

This is a bit confusing especially when testing. Maybe a pop-up message of some sort, or extending the no-connection text in the JSXC side-bar to try logging out and in again would help?

**Comment by MarcelWaldvogel** [comment]
I cannot reproduce this. Can you tell me more about your setup (browser, Nextcloud version, JSXC version, XMPP server (Prosody, I presume from #22))?

Can you try to clear localStorage (`localStorage.clear()` in the browser JavaScript console)? Does it help?

**Comment by poVoq** [comment]
Ok, sorry can't reproduce it now either with new users, but was causing me some confusion earlier on. Maybe it only effects NC users that had been created before activation of this bridge?

**Comment by MarcelWaldvogel** [comment]
When the users have been created should not affect the authentication. Let me know if it reappears.
