### ISSUE TITLE
Feature Request: Check app passwords

### ISSUE THREAD

**Issue by GIJack** [jsxc/xmpp-cloud-auth#32]
I have xmpp-cloud-auth successfully running on my nextcloud 12 install. I use the 2FA plugins, and I sync my apps with app passwords.

I would like this plugin to check app passwords as well for login. This is a great security feature, and right now, as it is setup, not only do App passwords not work, this plugin by-passes 2FA security present on nextcloud.

What I would like to see:

If 2FA is activated
1. Don't check main password(Unless 2FA, or OAUTH is somehow supported)
2. Check app passwords.

**Comment by sualko** [comment]
This will be possible with the upcoming 3.3.0 release of jsxc, see https://github.com/nextcloud/jsxc.nextcloud/releases/tag/v3.3.0-beta.1

**Comment by GIJack** [comment]
let me re-phrase. I am trying to log into jabber with an nextcloud app password. This still does not work.

I can access chat just fine through nextcloud.

I need your ejabberd script to check app passwords.

I am running the 3.3.0 release and it sill just only works with the primary password. This is annoying because it leaves ejabberd as a weak point in the chain

**Comment by MarcelWaldvogel** [comment]
Let me tell you what I just did. Then you tell me how that is different from what you expect or how it works for you.

Setup:
* Server
  - Ubuntu 16.04
  - Nextcloud 12.02
  - JSXC 3.3.0
  - Prosody 0.9.12
  - xmpp-cloud-auth jsxc/xmpp-cloud-auth@d9a527aeea65dda766eb2ea256517d3ab9418154
* Client:
  - Ubuntu 17.04
  - Gajim 0.16.6

Before the test started, Prosody already had a working setup for the server, but with the "standard" login password.

Actions:
1. In Nextcloud: Personal→App Passwords: Type "Gajim", click "Create new app password"
1. Copy this password (and click "Done" and deactivate file system access at some later point)
1. In Gajim: Account→Offline
1. Preferences→paste the password; "Done"
1. Account→Available: works
1. In Nextcloud: Delete that account password
1. In Gajim: Account→Offline; Account→Available: "Bad Password"

**Comment by GIJack** [comment]
Sorry for not getting back to you.

Server:
* Debian 9
* Nextcloud 12.0.2
* JSXC 3.3.0
* ejabberd 16.09
* xmpp-cloud-auth

Client:
* Arch Linux
* Pidgin 2.12.0

Before I started, chat was functioning with ejabberd linked, 2FA was setup for the account.

Created a new account in pidgin with the main account login, sans 2FA, and it logs in.
Created a new app password, and used the app password, and it does not work.
Change back to main password and it works.

No idea. It might be an ejabberd problem. Should I switch to prosody?
