### ISSUE TITLE
Update wiki tutorial

### ISSUE THREAD

**Issue by poVoq** [jsxc/xmpp-cloud-auth#39]
Or at least put a notice that it is severely outdated and you should rather use the installation.md

Also: for time limited tokens I need to uncomment that user.db line? is that directory writeable by the xcauth user by default?

**Comment by MarcelWaldvogel** [comment]
1. **Documentation:** The two instructions do focus on different users. [`doc/Installation.md`](https://github.com/jsxc/xmpp-cloud-auth/blob/master/doc/Installation.md) is a quick-setup guide for the experienced admin, while the [wiki](https://github.com/jsxc/xmpp-cloud-auth/wiki) should also be accessible to a more novice admin. We'd appreciate any help maintaining (or (re-)achieving) this goal.
2. **`user.db`:** Do you mean `cache-db`? That is only necessary for [user caching](https://github.com/jsxc/xmpp-cloud-auth/blob/master/doc/Cache.md). Tokens are always accepted by `xmpp-cloud-auth`; the setting in [JSXC for Nextcloud](https://github.com/nextcloud/jsxc.nextcloud) is only whether JSXC *uses* them for authentication.
3. **`/usr/lib/xcauth`:** Depends on how you set up your system. That directory needs to be created. [`install.sh`](https://github.com/jsxc/xmpp-cloud-auth/blob/master/install.sh) sets the permissions accordingly.
