### ISSUE TITLE
SSL3_GET_SERVER_CERTIFICATE:certificate verify failed

### ISSUE THREAD

**Issue by Ciangi** [jsxc/xmpp-cloud-auth#41]
SSL3_GET_SERVER_CERTIFICATE:certificate verify failed
2018-01-02 19:27:11,784 WARNING: An error occured during the request to https://xxxxxxxxxx/apps/ojsxc/ajax/externalApi.php for domain xxxxxxxxxx: [Errno 1] _ssl.c:510: error:14090086:SSL routines:SSL3_GET_SERVER_CERTIFICATE:certificate verify failed

How to not verify certificate ? 

Greetings.

**Comment by MarcelWaldvogel** [comment]
(You are running your own XMPP server, I presume.)

We do not plan to support deactivation. The days of self-signed certificates are over, thanks to [Let's Encrypt](https://letsencrypt.org/) now (and [DANE](https://netfuture.ch/2014/09/dane-the-ca-game-changer/) in the future).

If Let's Encrypt really is not an option for you, please do add the PEM-encoded root certificate of your own CA to `/etc/ssl/certs` and then run `c_rehash` or `openssl rehash` (to make them available to most applications) and append it to `/etc/ssl/certs/ca-certificates.crt` (which the Python `requests` library consults on some platforms).

**Comment by MarcelWaldvogel** [comment]
If you insist you want to disable SSL certificate verifications completely (which defeats most of the purpose of using HTTPS in the first place, so you probably **do not want to do this**):

Append `self.session.verify=False` to the end of `xcauth.__init__` in `xclib/__init__.py`

**Comment by Ciangi** [comment]
Finally, i found that from company that i bought ssl certs, if i want to use my own server i have to install two .pem CA files. So it's mean that i have to add this two files into /etc/ssl/certs directory and then run c_rehash right?

But what if I use nextcloud on docker? i have to add this two files to /etc/ssl/certs into host server, then into /etc/ssl/certs nextcloud docker container and finally into /etc/ssl/certs prosody docker container??

On host server and nextcloud container i use Apache and till now i just downloaded the .key and .cert file and add them into apache configuration of host and nextcloud. And when i type: https://mydomain.com Firefox, chrome etc. show me that connection is secure... so if i good understand the certificate is verified.... isn't it?

**Comment by MarcelWaldvogel** [comment]
Adding to `/etc/ssl/certs` is only necessary when your server's certificate is *not* based on one of the ~300 global root certificates (the ones which are also in your browser). And then you add the root CA's certificate, not your server certificate.

You add the

* server certificate (including private key) and
* intermediary certificates (if any, as seems to be the case with you; the certificates in the chain between one of the global roots and your server certificate)

to whichever server does the encryption (the Apache server that does have the `SSL*` configuration options). My [Apache configurations](http://httpd.apache.org/docs/current/mod/mod_ssl.html) include
```apache
SSLEngine             on
SSLProtocol           all -SSLv2 -SSLv3
SSLCipherSuite        EECDH+ECDSA+AESGCM:EECDH+aRSA+AESGCM:EECDH+ECDSA+SHA384:EECDH+ECDSA+SHA256:EECDH+a
RSA+SHA384:EECDH+aRSA+SHA256:EECDH+aRSA+RC4:EECDH:EDH+aRSA:RC4:!aNULL:!eNULL:!LOW:!3DES:!MD5:!EXP:!PSK:!SR
P:!DSS:!RC4
SSLHonorCipherOrder   on
SSLCompression        off
SSLOptions            +StrictRequire
SSLCertificateFile    /etc/acme/example.com/fullchain.cer
SSLCertificateKeyFile /etc/acme/example.com/example.com.key
```
where `fullchain.cer` includes the contents of both `*.pem` files.

When your browser checks out fine, it should also check out fine with `xmpp-cloud-auth`.
