### ISSUE TITLE
.

### ISSUE THREAD

**Issue by gurussia** [jsxc/xmpp-cloud-auth#48]
FUCKING SHIT:

Why peoples are getting bad:
https://github.com/jsxc/jsxc/wiki/Install-ejabberd-(owncloud)-%7C-Ubuntu-12.04

Hi guys

Maybe this is the last message i'm gonna write here. Direct message: 

Here is the manual: https://github.com/jsxc/jsxc/wiki/Install-ejabberd-(owncloud)-%7C-Ubuntu-12.04

This manual is SHIT and obsolete. Why it is not deleted nobody know. But this manual don't have obsolete, obsolete is in enter in the readme WITH small letters. Who is gonna see small letters. :warning: This manual is outdated! :warning:

Check ejabberd-cloud-auth or Modern ejabberd configuration instead.

The new NON WORKING is ejabberd-cloud-auth: This new NON-WORKING manual is here: https://github.com/jsxc/xmpp-cloud-auth/wiki

Now linux is where you want to install directory. In this NON WORKING manual they don't comment where it has download THIS SHIT: On the XMPP server: For ejabberd installations

apt install ejabberd git python-bcrypt
cd /opt
git clone https://github.com/jsxc/xmpp-cloud-auth

So if you have ejabberd in /etc/magazin/html/ejabberd -> download xmpp-cloud-auth here

cd  /etc/magazin/html/ejabberd
git clone https://github.com/jsxc/xmpp-cloud-auth

and after git download, you will have: /etc/magazin/html/ejabberd/xmpp-cloud-auth

Lets continue:
NOw i wants again to say thank let's encrypt that you help humankind have FREE ssl.

Now this ejabberd.yaml is OBSOLETE:https://github.com/jsxc/xmpp-cloud-auth/wiki/ejabberd

If you follow it, you will get error when you start ejabberdctl start i open issue and something happend, include there was intent negative comments. 

On the next page here: https://github.com/jsxc/xmpp-cloud-auth/wiki/nextcloud
It is unclear if PEOPLES need to install bosh or http-bind. Now if i remember past year 2017 i test ejaberrd with version 17x in the moment i don't rememeber and it was working, in the moment i remember when i try start ejabberdctl start it comment http-bind is obsolete and change it to BOSH.

So what SHIT is neccesary. http-bind or BOSH. In ejabberd they comment bosh and http-bind are different. How i say in upper of this two lines, when it start ejaberdxctl start it comment http-bind is obsolete, chante to BOSH. But in this manual they comment: https://github.com/jsxc/xmpp-cloud-auth/wiki/nextcloud " here it comment http-bind " Inhuman, in new version ejabberd 18x.x it comment http-bind IS OBSOLETE, in past year 2017 it comment if i remember version 17x it comment http-bind IS OBSOLETE. 

NOw lets continue on the next page: https://github.com/jsxc/xmpp-cloud-auth/wiki/ejabberd-extauth

Pfuuuuuu, the other day i repeat this SHIT /opt/xmpp-cloud-auth/xcauth.conf > /etc/xcauth.conf
 i repeat it again and again, and again and nextcloud xmpp client comment ERROR IN AUTENTICATION, include it comment other error start start spooling error every less 1 second. I tell marcel and marcel comment that they don't have this issue and if they don't have this issue they will not repair it. So Next: Enjoy your fully JSXC-chat-enabled Nextcloud! > FOR WHAT.

Now conclusion. Obsolet, misunderstanding, missing step by step information, inhuman comments. Include they comment manual for owncloud/nextcloud press here and it comment ARCHIVE and when you open it comment with SMALL WORDS obsolete, click here for new authentication SHIT how you see in this message it don't work. It was looking all day how to be solved this SHIT, so why it need to share solution, when there is peoples who BADLY TREAT OTHERS PEOPLES. half explain, mis-understanding, LYING, press here do this... and final you broke your ubuntu server. All day i was looking how to solve my friend xmpp nextcloud client app, becouse nextcloud server HAS BUG, when SHIT jsxc is enabled in nextcloud, but marcel comment they don't have this issue and they will NOT solve it. So why it have to put SOLUTION when THIS SHIT bug is from year 2016 and more than 2 months.

**Comment by sualko** [comment]
https://github.com/jsxc/jsxc/blob/master/CODE_OF_CONDUCT.md
