### ISSUE TITLE
Omemo message from android conversations to Nextcloud JSXC, not supported? or if so how do I enable it.

### ISSUE THREAD

**Issue by xekon** [jsxc/xmpp-cloud-auth#52]
I setup my ejabberd server to properly work with Omemo and Conversations for android.

I have Nextcloud JSXC external auth working, but not with OMEMO encryption on
Nextcloud chat receives a message that looks like this:

    I sent you an OMEMO encrypted message but your client doesn’t seem to support that. Find more information on https://conversations.im/omemo

Any help or information is appreciated.

**Comment by xekon** [comment]
I just found this: https://github.com/jsxc/jsxc-plugin-omemo

Is integrating this the current solution for Omemo in Nextcloud XMPP chat?

**Comment by sualko** [comment]
It will be integrated into JSXC 4.0 and we are hoping to release a first alpha version in the next weeks or months.
