### ISSUE TITLE
using chat app in nextcloud with external server on hosted server

### ISSUE THREAD

**Issue by daniu-de** [jsxc/xmpp-cloud-auth#53]
Hi,
I have an installation of nextcloud on a hosted server and would like to use the chat app to communicate with other xmpp servers. Is that possible? For example I would like to use the service of jabber.hot-chilli.net.

Of course I do not have access to a terminal on the server.

**Comment by MarcelWaldvogel** [comment]
`xcauth` needs to be run on the XMPP server, so you need control over that one. According to your description, I presume this is not the case.

If the Nextcloud installation is just for a couple of users, then it is possible to manually configure account information in your Nextcloud instance. Easiest: each user does this when logged in; alternative: populate Nextcloud settings (copy and adapt what has been set for the first user).

You can also use our managed server, which essentially automatically configures our XMPP server for you.

**Comment by daniu-de** [comment]
Hi,

thanks for the quick answer!

probably I do not get what you mean but seems like I do not have the required permissions.

Do I also need this permissions to use your managed server? I tried to set that up. The chatsoftware asks me to log in after nextcloud login. My username is prefilled in the form and the passwort as well but the password is not accepted. What do I need to fill in?

regards

**Comment by MarcelWaldvogel** [comment]
Our Managed Server self-configures based on the requests, so there is no need for you to have shell access to it.

For the Managed Server, passwords are avoided. Instead, short-term tokens are used. Can you tell me more about your setup and what failed? (Information that you do not want to see archived in that ticket can also go to marcel@jsxc.org)

**Comment by MarcelWaldvogel** [comment]
Could you please resend your mail? I have received it, but cannot find it anymore. Sorry!

**Comment by sualko** [comment]
I close this issue due to inactivity. Please reopen if needed.

**Comment by daniu-de** [comment]
Hi,
sorry for the delay - tried it again today but still not working - I setup the managed service and it tells me that it went alright. Then I try to open the chat and it asks me for a username and password while both is filled in already. However when I just click OK I get an error message: "Der Chatserver hat die Anmeldung abgelehnt. Falsches Passwort?" - english something like: "the chatserver has denied your registration". Signing in and out of Nextcloud does not help - I am using the latest version of Nextcloud and all apps.
regards

**Comment by MarcelWaldvogel** [comment]
Today, we had trouble with the registration for the managed service. Unless you tried it in the 20 minutes before posting, there should have been no success for registration.

Looking into the logs, I cannot see any authentication failures today.

Can you give me more information? Browser logs?

**Comment by daniu-de** [comment]
Hi,
I guess I did try in the 20min before posting ... Registration does not fail.

I get: Congratulations! You got your own XMPP server. Please log out and in again.

Could you at first tell me whether it is correct that I just need to hit login with the filled in form after registering and opening the chat? I don't know how I could possibly give you browser logs. But my server-domain is die*****.net. Just tried again but it did not work again - chat tells me first that I am not connected, when I hit sign in again I get the window with my username and a *** password - hitting Connect ("Verbinden") gives me the above message: "... wrong password?"

Settings in nextcloud are:
URLs: stun:turn.jsxc.ch, turn:turn.jsxc.ch
TURN Username: nextcloud.die*****.net (the url of nextcloud)
TURN Credentials: empty
TURN Secret: some characters
TURN TTL: 8640

regards

**Comment by MarcelWaldvogel** [comment]
Sorry, slipped under the radar. Is this still an issue?

**Comment by daniu-de** [comment]
No - it is working now ... most of the time ;-)
