### ISSUE TITLE
xcdbm.py and KEY/VALUE with multiple Domains

### ISSUE THREAD

**Issue by bsfd80** [jsxc/xmpp-cloud-auth#54]
Hello,

I want to use more then one cloud instance and more domains.

./xcdbm.py -c /etc/xcauth.conf -b /var/lib/xcauth/dynamic-domains.db -u nextexturl -s secrettoken -P
KEY VALUE
Whats KEY and VALUE and how to use it with prosody?

(With -G KEY I can view the VALUE)

With one domain and instance, without /var/lib/xcauth/dynamic-domains.db it works nice.
How to setup, more then one domain/instances?

When I set any KEY and VALUE, I get this error:
Could not authenticate user user@seconddomain.tld: noauth

Thanks, 4 help,
bsfd80

/etc/xcauth.conf

type=prosody
secret=secrettoken1
url=externalapiurl1
timeout=5
domain-db=/var/lib/xcauth/dynamic-domains.db
log=/var/log/xcauth
cache-query-ttl=4h
cache-verification-ttl=1d
cache-unreachable-ttl=1w
#debug

**Comment by MarcelWaldvogel** [comment]
I'm glad you are enjoying JSXC to go for your second domain! Congratulations!

Keys and values are documented in https://github.com/jsxc/xmpp-cloud-auth/blob/master/doc/Database.md#domain-db

BTW: You do not need to specify any values to `xcdbm` that are already in `/etc/xcauth.conf`. So the command would just be
```
./xcdbm.py -P seconddomain.tld '<SECRET>\thttps://seconddomain.tld/index.php/apps/ojsxc/ajax/externalApi.php\tseconddomain.tld\t'
```
where \t should be a TAB (entered with ^V<TAB> on some shells).

I do maintain a file with all key/value pairs and then load it  `-L` from stdin:
```
seconddomain.tld<TAB><SECRET><TAB>https://seconddomain.tld/index.php/apps/ojsxc/ajax/externalApi.php seconddomain.tld<TAB>
thirddomain.tld<TAB><SECRET><TAB>https://thirddomain.tld/index.php/apps/ojsxc/ajax/externalApi.php thirddomain.tld<TAB>
```
(For most users, the key and the third value will be the same.)

If there is a match against any of the keys in the database, `secret` and `url` from the configuration file will be ignored; i.e., it is used for fall-back only.

Prosody/ejabberd use: The use for the second domain will be the same as for the first. The XMPP domain is passed to `xcauth` in any of the requests, so it will be able to distinguish between the different domains automatically.
