### ISSUE TITLE
documentation incorrect - external_cloud.sh - no such thing

### ISSUE THREAD

**Issue by NESC1US** [jsxc/xmpp-cloud-auth#61]
Hello Marcel,

I think you forgot to update wiki on https://github.com/jsxc/xmpp-cloud-auth/wiki/ejabberd which shows wrong config when compared to another of your [wiki](https://github.com/jsxc/xmpp-cloud-auth/blob/master/doc/Installation.md) of the actual git repository:
```
extauth_program: "/opt/xmpp-cloud-auth/external_cloud.sh"
```
should be, according to [this](https://github.com/jsxc/xmpp-cloud-auth/blob/master/doc/Installation.md#ejabberd):
```
extauth_program: "/opt/xmpp-cloud-auth/xcauth.sh"
```

**Comment by MarcelWaldvogel** [comment]
Thanks for pointing it out. Fixed it in four other wiki entries as well!
