### ISSUE TITLE
Changing auth method from sql to external

### ISSUE THREAD

**Issue by Thomas301263** [jsxc/xmpp-cloud-auth#64]
HI,
in my case Nextcloud 13.0.4
ejabberd 16.01
mariadb 10.1.34
php 7.0
Nextcloud 13.0.4
is running.
I tried to change authentication from sql to external but that will not work.
I like to get such a synchronisation of password with nextcloud and ejabberd if a new user
will be created or a user changes the password.
Is there a way to get that working together with sql or do I have to change the password manually like before?
I already tried it with xcauth but without success.
Thanks for helping

**Comment by MarcelWaldvogel** [comment]
Let me summarize what I believe I understand:

1. You had a Nextcloud running (with user management from within Nextcloud)
1. You had ejabberd running with everything (including users) stored in MariaDB.
1. I presume this were the same users in both installations, but with potentially diverging passwords.
1. You want to change ejabberd so the accounts (and therefore passwords) are all maintained by Nextcloud only
1. You did not get that to work

* Is this correct?
* What was the configuration like before/after?
* How is "that will not work" defined? What did not work? What error messages are you getting (please also check the logs in `/var/lib/xcauth/*`

**Comment by MarcelWaldvogel** [comment]
Can we close this issue?
