### ISSUE TITLE
Unable to connect on a Nextcloud account

### ISSUE THREAD

**Issue by danicotillas** [jsxc/xmpp-cloud-auth#68]
I have my own nextcloud account on https://caracol.nodocomun.org.
I have installed Javascript XMPP chat and try to connect via mobile phone with Xabber.
I write down my username: daniel and the server: caracol.nodocomun.org and it doesn´t connect.

What am I doing wrong?

Thanks

cc @MarcelWaldvogel 

![photo_2018-08-23_13-20-27](https://user-images.githubusercontent.com/7635775/44522585-5213aa00-a6d7-11e8-8ae5-53a272e4a745.jpg)
![photo_2018-08-23_13-20-28](https://user-images.githubusercontent.com/7635775/44522586-5213aa00-a6d7-11e8-85d6-ab0f08857913.jpg)

**Comment by sualko** [comment]
I assume you use the managed backend and therefore you have to use `daniel@caracol.nodocomun.org.jsxc.ch`.

**Comment by danicotillas** [comment]
It doesn´t work :(

**Comment by sualko** [comment]
I see that you can enlarge the error message in the above screenshot. What does it say? Do you use the managed backend?

**Comment by danicotillas** [comment]
![photo_2018-08-23_13-40-27](https://user-images.githubusercontent.com/7635775/44523436-1e864f00-a6da-11e8-9669-7de271c120b2.jpg)
![photo_2018-08-23_13-40-29](https://user-images.githubusercontent.com/7635775/44523437-1e864f00-a6da-11e8-8b34-70bda7f36502.jpg)

**Comment by sualko** [comment]
You try to connect to `caracol.nodocomun.org` and not `caracol.nodocomun.org.jsxc.ch`.

**Comment by sualko** [comment]
But to be precise: If you use our managed server you have to connect to `xmpp.jsxc.ch` with a jid `yourName@caracol.nodocomun.org.jsxc.ch`. But it could be also the case that there is a problem with our registration server. Marcel will check that asap.

**Comment by MarcelWaldvogel** [comment]
How did you configure the JSXC app inside Nextcloud? The default is the local server, that can neither support other clients nor be part of the federation.

If you activate the [Managed Server](https://www.jsxc.org/managed.html) in the JSXC admin settings within Nextcloud, you probably will get back a domain like nodocomun.jsxc.ch.

If you [set up your own XMPP server on a fresh Raspberry Pi](https://github.com/jsxc/xmpp-cloud-auth/wiki/raspberry-pi-en) or [in any other setup](https://github.com/jsxc/xmpp-cloud-auth/wiki), you will get whatever you set up your DNS to.

**Comment by danicotillas** [comment]
Ooooook! I didn´t do all that steps. I have checked it but it doesn´t work properly. I have to take more time to review. Thanks a lot!
