### ISSUE TITLE
install on Manjaro / Arch

### ISSUE THREAD

**Issue by scurrvy2020** [jsxc/xmpp-cloud-auth#71]
I'm trying to install this on Arch.  I have everything setup and modified the files as needed.  When I execute /opt/xmpp-cloud-auth/xcauth.py  I get this output:

`Traceback (most recent call last):
  File "./xcauth.py", line 3, in <module>
    from xclib.configuration import get_args
  File "/opt/xmpp-cloud-auth/xclib/__init__.py", line 4, in <module>
    from xclib.sigcloud import sigcloud
  File "/opt/xmpp-cloud-auth/xclib/sigcloud.py", line 1, in <module>
    import urllib.request, urllib.parse, urllib.error
ImportError: No module named request
`
It looks like a python problem to me (this is with python2 shebang).  it looks like it isn't able to import the modules included in the package.  I've tried adding to $PYTHONPATH and using sys.path, but I still get errors.

**Comment by scurrvy2020** [comment]
Okay, I've figured a little bit out.  It looks like in python 3.7 `async` is no longer valid and it needs to be changed to `async_`.  https://github.com/pypa/pipenv/issues/956

I made those changes to a few of the files and I'm able to get it to run without errors.  My service is still failing though.

**Comment by scurrvy2020** [comment]
Okay, got it working!  Manjaro also needs `python-systemd` as a dependency.

**Comment by MarcelWaldvogel** [comment]
Can you list your changes? (e.g., as a pull request)

**Comment by MarcelWaldvogel** [comment]
The standard workflow (unfortunately, not as simple as I would like):

1. Fork the repository
1. Check out your fork
1. (Optional:) Create a feature branch with e.g. `git checkout -b python37-compatibility`)
1. Normal edit, commit, push
1. In the web interface of your fork, the option to create a pull request will be highlighted as a yellow bar above the code

https://help.github.com/articles/creating-a-pull-request/

**Comment by scurrvy2020** [comment]
I think I got it. Thanks for the bit of guidance.

**Comment by MarcelWaldvogel** [comment]
Ah, just noticed you already did, but (accidentally, I believe) closed the pull request.
