### ISSUE TITLE
Can’t login after activating managed xmpp server

### ISSUE THREAD

**Issue by mouseb** [jsxc/xmpp-cloud-auth#77]
[[duplicating from the nc forums](https://help.nextcloud.com/t/cant-login-after-activating-managed-xmpp-server/48912) as requested. one other user also mentioned having the same issue.]

hi,

i run nc 14. i activated the jsxc managed xmpp server option as per https://www.jsxc.org/managed.html with the aim of being able to use the app via mobile clients.

but once i’ve successfully registered and received my xmpp domain, i am no longer able to log in to the chat app at all, even in the nc web interface. authentication fails and the pword window asks me if perhaps my pword is incorrect (“Authentication failed with the chat server. Maybe the password is wrong?”), but it isn’t, as it is my usual nc one, and i’m logged into nc.

one thing i noticed that seemed a bit strange about the domain: i use a subdomain like gg.example.com, but the domain for xmpp is given only as gg.jsxc.ch, not gg.example.jsxc.ch. cd that be an issue? this contradicts the managed FAQ, but is automatically decided on when registering so i can’t change it.

actually, if relevant, my nc instance is actually at gg.example.com/nextcloud. not sure if that cd make any diff.

if i disable the managed xmpp server, chat logs in again fine next nc login.

appreciate any help / mayb it is helpful for the app devs to know about it.

thanks,
m

**Comment by kernelguru** [comment]
Yep, have the same issue!

**Comment by MarcelWaldvogel** [comment]
@sualko: This seems like an app problem, not a managed server problem (as well): If connection to the XMPP server should fail, logging in should still be possible.

@mouseb: Yes, indeed, we decided to shorten the URL when possible and forgot to update the documentation. I am trying to guess your real domain name from your abbreviation and the `/nextcloud` path component. In case you used a German word related to "gg" and registered on Wednesday afternoon: I have not seen any login attempts for that domain on the server.

So it might have been a connection problem, not an authentication problem. However, I made sure that the server reread its configuration file, could you (and @kernelguru) try again?

If you want to give me more information for debugging you prefer not to share publicly, you can reach me at marcel@jsxc.ch.

**Comment by kernelguru** [comment]
Now its gonna working:)

Marcel Waldvogel <notifications@github.com> schrieb am Mo. 11. März 2019 um
17:08:

**Comment by MarcelWaldvogel** [comment]
Looking further, I have noticed that an ejabberd update on the server a few days ago changed the permissions of the configuration directory, so the registration process could not update the configuration information (and thus did not learn about the additional domains).

This has been fixed, so re-enabling the managed server should work now (you may have to re-register in the UI, but it will be much faster as the first time, as all the certificates have already been issued). Sorry for the inconvenience!

Just for clarification: Nextcloud login was not prevented by the "Password wrong?" message, it was only when clicking on "reconnect" in the JSXC sidebar or from a third-party XMPP app?

**Comment by MarcelWaldvogel** [comment]
OK, I'll close it for now. Reopen if it reappears or it blocked Nextcloud login.
