### ISSUE TITLE
New users can't add contacts

### ISSUE THREAD

**Issue by sualko** [jsxc/xmpp-cloud-auth#8]
from jsxc/jsxc#506 @wargreen

> Hi,
with 3.2.0 beta in nextcloud, new users can't add any contacts.
The extauth.log file show "2017-04-06 16:28:54,639 INFO: Receive operation isuser" at each try, but nothing more happen in any logs.
>
> Old users can add theses users and tchat.

**Comment by sualko** [comment]
@wargreen Once again, thanks for reporting. In ejabberd the `isuser` operation was not needed and therefore I didn't implement it. I will fix it asap.

**Comment by mejo-** [comment]
Hey sualko, do you have any estimation when you find time to work on this issue? Just a humble question :)
