### ISSUE TITLE
Nextcloud XMPP Managed (Beta service) not working

### ISSUE THREAD

**Issue by copybotclub** [jsxc/xmpp-cloud-auth#82]
Nextcloud version 16.0.4
Xmpp beta (managed) doesn't work

Hello, I've been warned that chat on our Nextcloud instance stopped working. Uppon checking it I could confirm that wouldn't even let me login after I've put the credentials
Meanwhile I could see 2 days ago that jsxc.ch was down.

Can you please tell me what can I do to have it restored or when can you have the managed service ready

TIA

**Comment by MarcelWaldvogel** [comment]
Sorry, an unfortunate series of events occurred. I hope to finish fixing the problem cascade tomorrow. Sorry for any inconvenience. (Vacation, fiber optic converters dying, DHCP servers misbehaving, DNS servers not updating, to name the most important problems)

**Comment by MarcelWaldvogel** [comment]
I'm still fighting with some DNS problems, but after yesterday's changes should have propagated everywhere, they should no longer affect you. Could you please retest and confirm? Thanks!

**Comment by copybotclub** [comment]
Thank you for your reply, I thought it was on our side.
I hope you can fix them soon

**Comment by MarcelWaldvogel** [comment]
Does it work for you again?

**Comment by copybotclub** [comment]
Yes it seems solved
Login ok
sending and receiving messages ok
login with adium (mac app) also ok
